//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_thaotaccsdl.cms.admin.SanPham.QuanLySize.Ajax {
    
    
    public partial class Size {
    }
}
